language: python
addons:
    apt:
        packages:
            - graphviz
            - fonts-ipafont
python:
  - "3.6"
install: "pip install -q -r requirements.txt"
script: sphinx-build -E -nW -b html -d build/doctrees source build/html
before_deploy:
  - "touch build/html/.nojekyll"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build/html
  on:
    branch: master
