language: python
python:
  - "3.6"
before_install:
  - "sudo apt-get install graphviz"
install: "pip install -q -r requirements.txt"
before_script:
  - "export LANG=ja_JP.UTF-8"
script: sphinx-build -E -nW -b html -d build/doctrees source build/html
before_deploy:
  - "touch build/html/.nojekyll"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build/html
  on:
    branch: master
